spring.application.name=payment-system

mongo.properties.config.connectionUrl:mongodb://fraudUser:fraudPassword@localhost:27017/fraudDetectionDB
mongo.properties.config.authDb:admin
mongo.properties.config.username:
mongo.properties.config.pass: