spring.application.name=payment-system

# Database configuration
spring.datasource.jdbc-url=jdbc:mysql://localhost:3306/payment_service
spring.datasource.username=root
spring.datasource.password=18sep2000*
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


stripe.secret.key=${secret_key}
#stripe.public.key=${public_key}
#stripe.api.key=rk_test_51Qxp74BTS3g9NVDlgbA2f2z0MuzkvuW6hmQDg8nvph9FarHwfIiRieoPtRX1wqSRSRwNa3ynrjCwxtxfOaCnMsuw00Yi8ECAMC

logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
